name: CheckDeath
author: CounterCrysis
version: 0.2.3
main: me.countercrysis.checkdeath.CheckDeath
description: Allows you to check the details of a players death, such as what items they had.
api-version: 1.13
commands:
  checkdeath:
    description: Check a player death.
    usage: /<command>
    permission-message: You don't have <permission>