name: CheckDeath
author: CounterCrysis
version: 0.1.0
main: me.countercrysis.checkdeath.CheckDeath
description: Allows you to check the details of a players death, such as what items they had.
commands:
  checkdeath:
    description: Check a player death.
    usage: /<command>
    permission: checkdeath
    permission-message: You don't have <permission>